apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  landscape: local
resources:
  - kafka.yml
  - zookeeper.yml
  - postgres.yml
  - redis.yml
  - configmap.yml
configMapGenerator:
  - name: init.sql
    files:
      - init.sql